<a href="https://colab.research.google.com/github/KARTHIKAKRISHNA123/AIML_Learnings/blob/main/ANN_with_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("tensor_flow_version", tf.__version__)
print("keras_version", tf.keras.__version__)

tensor_flow_version 2.19.0
keras_version 3.13.2


In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data = load_iris()
x = data.data
y = data.target.reshape(-1, 1)



In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [ ]:
x.shape

(150, 4)

In [ ]:
y.shape

(150, 1)

In [ ]:
#one hot encoding - as output is categorical
enc = OneHotEncoder(sparse_output=False)
y = enc.fit_transform(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation = "relu", input_shape=(4,)),
    tf.keras.layers.Dense(4, activation = "relu"),
    tf.keras.layers.Dense(3, activation = "softmax")]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 91 (364.00 B)

 Trainable params: 91 (364.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
4 * 8 + 8

40

4 * 8 + 4


1 * 4 + 1

In [ ]:

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]) # Corrected loss and metrics format

In [ ]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"]) # Corrected loss function
model.fit(x_train, y_train, epochs=1000, verbose=2)

Epoch 1/1000
4/4 - 2s - 526ms/step - accuracy: 0.9167 - loss: 0.3816
Epoch 2/1000
4/4 - 0s - 37ms/step - accuracy: 0.9333 - loss: 0.3779
Epoch 3/1000
4/4 - 0s - 22ms/step - accuracy: 0.9167 - loss: 0.3752
Epoch 4/1000
4/4 - 0s - 37ms/step - accuracy: 0.9167 - loss: 0.3725
Epoch 5/1000
4/4 - 0s - 20ms/step - accuracy: 0.9083 - loss: 0.3701
Epoch 6/1000
4/4 - 0s - 21ms/step - accuracy: 0.9083 - loss: 0.3683
Epoch 7/1000
4/4 - 0s - 21ms/step - accuracy: 0.9083 - loss: 0.3652
Epoch 8/1000
4/4 - 0s - 37ms/step - accuracy: 0.9417 - loss: 0.3642
Epoch 9/1000
4/4 - 0s - 24ms/step - accuracy: 0.9500 - loss: 0.3611
Epoch 10/1000
4/4 - 0s - 23ms/step - accuracy: 0.9500 - loss: 0.3589
Epoch 11/1000
4/4 - 0s - 20ms/step - accuracy: 0.9500 - loss: 0.3567
Epoch 12/1000
4/4 - 0s - 42ms/step - accuracy: 0.9500 - loss: 0.3555
Epoch 13/1000
4/4 - 0s - 22ms/step - accuracy: 0.9500 - loss: 0.3535
Epoch 14/1000
4/4 - 0s - 24ms/step - accuracy: 0.9417 - loss: 0.3507
Epoch 15/1000
4/4 - 0s - 22ms/step - accur

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - accuracy: 1.0000 - loss: 0.0307


In [ ]:
print("Loss Of My ModeL: ", loss)
print("Accuracy Of My Model: ", accuracy)

Loss Of My ModeL:  0.03070768527686596
Accuracy Of My Model:  1.0
